require 'rumx/beans/folder'
require 'rumx/beans/message'
require 'rumx/beans/timer'
require 'rumx/beans/error'
require 'rumx/beans/timer_and_error'
require 'rumx/beans/hash'
require 'rumx/beans/timer_hash'
